[package]
name = "manga_impression"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlx = { version = "0.6", features = [ "runtime-actix-rustls", "sqlite" ] }
anyhow = "1.0"
tokio = { version = "1.24", features = ["full"] }
