[package]
name = "manga_impression"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlx = { version = "0.6", features = [ "runtime-actix-rustls", "sqlite", "chrono" ] }
rfd = { version = "0.10" }
egui = { version = "0.20" }
eframe = { version = "0.20" }
anyhow = "1.0"
tokio = { version = "1.24", features = ["full"] }
chrono = { version = "0.4" }
dotenvy = { version = "0.15" }
crossbeam = { version = "0.8" }
